on:
  push:
    tags:
      - "*"

name: RUN BUILD
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: flatpak action
      uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: com.deepinwine6.stable.flatpak
        manifest-path: com.deepinwine6.stable.json
        cache-key: flatpak-wine60525

    - name: Release set path
      run: |
        touch release.txt
        # echo "🔗 [cloudupload](${{ steps.cloudupload.outputs.url }})" >> release.txt
        echo "RELEASE_PATH=$PWD" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.RELEASE_PATH }}/*.flatpak
        bodyFile: release.txt
        token: ${{ secrets.GITHUB_TOKEN }}
